services:
  app:
    build: ./
    container_name: notes-app
    # command: "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "8081:8081"
    environment:
      - SQLITE_PATH=/sqlite.db
    # volumes:
    #   - "./static:/code/app/static/"
    #   - "./data/sqlite.db:/sqlite.db"
    